apiVersion: v1
kind: Service
metadata:
  name: newsapp-svc
  namespace: newsapp-ns
  labels:
    app: newsapp-svc
    lang: all #select all languages
  
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: newsapp