apiVersion: v1
kind: Service
metadata:
  name: newsapp-svc-go
  namespace: newsapp-ns
  labels:
    app: newsapp-svc
    lang: go

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      #protocol: TCP
  selector:
    app: newsapp
    lang: go