apiVersion: v1
kind: Service
metadata:
  name: newsapp-svc-nodejs
  namespace: newsapp-ns
  labels:
    app: newsapp-svc
    lang: nodejs

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      #protocol: TCP
  selector:
    app: newsapp
    lang: nodejs