apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: newsapp-nodejs
  namespace: newsapp-ns
  labels:
    app: newsapp
    lang: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsapp
  template:
    metadata:
      labels:
        app: newsapp
        lang: nodejs
    spec:
      containers:
        - image: balanus/newsapp:nodejs-v2
          name: newsapp
          env:
          - name: PORT
            value: "3000"
          ports:
            - containerPort: 3000
              name: newsapp
          imagePullPolicy: Always
