apiVersion: v1
kind: Service
metadata:
  name: newsapp-svc-python
  namespace: newsapp-ns
  labels:
    app: newsapp-svc
    lang: python
  
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 5000
      #protocol: TCP
  selector:
    app: newsapp
    lang: python
