apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: newsapp-python
  namespace: newsapp-ns
  labels:
    app: newsapp
    lang: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsapp
  template:
    metadata:
      labels:
        app: newsapp
        lang: python
    spec:
      containers:
        - image: balanus/newsapp:python-v1
          name: newsapp
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "5000"
          ports:
            - containerPort: 5000
              name: newsapp
