apiVersion: networking.istio.io/v1alpha3
kind: Gateway

metadata:
   name: newsapp-ingress
   namespace: newsapp-ns

spec:
   selector:
      istio: ingressgateway
   servers:
   - hosts:
     - "*"
     # - newsapp-svc-python.newsapp-ns.svc.cluster.local
     # - newsapp-svc-nodejs.newsapp-ns.svc.cluster.local
     port:
        number: 80
        protocol: http
        name: HTTP
